### ISSUE TITLE
Drush Command Issue

### ISSUE THREAD

**Issue by rhache** [stef-van-looveren/learning-drupal-as-a-framework#10]
When I run the the `drush offer-create-seeds` command, I get the following error in the terminal:

```
  Command "offer-create-seeds" is not defined.  
```

However if I move the following code from the `offer.services.yml` into a `drush.services.yml` in the offer module folder it works:
```
services:
  offer.commands:
    class: \Drupal\offer\Commands\SeedGeneratorCommand
    tags:
      - { name: drush.command }
```

The only issue, and I'm not sure if it matters at this point, is you get the following error after running the drush command:
```
In Query.php line 141:
                                                                                  
  Entity queries must explicitly set whether the query should be access checked   
  or not. See Drupal\Core\Entity\Query\QueryInterface::accessCheck().  
```
